# https://collabnix.com/docker-compose-cheatsheet/
# https://tuto.grademe.fr/inception/

version: '3.8'



services:
  


  mariadb:
    build: requirements/mariadb/ -t .
    container_name: mariadb
    image:
    ports:
      -3306



  # ngnix:
  #   build: requirements/ngnix/ -t .
  #   container_name: ngnix
  #   image:
  #   ports:
  #     -3306


  # wordpress:
  #   image:

  #   depends_on:
  #     - ngnix



networks:
  my-network:
    driver: bridge


